I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 350, in script
    Extra "Me pergunto se está havendo uma epidemia de gripe. O tempo esfriou ultimamente…"
Exception: Sayer 'Extra' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 350, in script
    Extra "Me pergunto se está havendo uma epidemia de gripe. O tempo esfriou ultimamente…"
  File "D:\visual novel\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\visual novel\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Extra' is not defined.

Windows-10-10.0.19041 AMD64
Ren'Py 8.0.3.22090809
Nekrós 1.0
Sat Mar 25 20:30:53 2023
